# Generated by Django 3.1.7 on 2021-12-06 17:10

import django.contrib.gis.db.models.fields
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('tb_ciclo_monitoramento_id', models.IntegerField()),
                ('sg_uf', models.CharField(max_length=2)),
                ('no_estagio', models.CharField(max_length=255)),
                ('no_imagem', models.CharField(max_length=255)),
                ('dt_imagem', models.DateField()),
                ('nu_orbita', models.CharField(max_length=3)),
                ('nu_ponto', models.CharField(max_length=3)),
                ('dt_t_zero', models.DateField()),
                ('dt_t_um', models.DateField()),
                ('nu_area_km2', models.FloatField()),
                ('nu_area_ha', models.FloatField()),
                ('dt_cadastro', models.DateTimeField()),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4674)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BasicElasticStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('bulk_size_request', models.IntegerField(default=1000)),
                ('structure', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
        ),
    ]
