# Generated by Django 3.1.7 on 2021-12-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicelasticstructure',
            options={'ordering': ['url', 'identifier']},
        ),
    ]
