# Generated by Django 3.1.7 on 2022-02-09 18:21

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ('url', 'identifier')},
        ),
        migrations.AlterField(
            model_name='structure',
            name='bulk_size_request',
            field=models.IntegerField(default=1000, verbose_name='Bulk size per request'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='identifier',
            field=models.CharField(max_length=255, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='index',
            field=models.CharField(max_length=255, verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='structure',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Json Structure'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Structure url'),
        ),
    ]
